/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as ConsoleNewRouteImport } from './routes/console.new'
import { Route as ConsoleFunctionIdRouteImport } from './routes/console.$functionId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/console/',
  path: '/console/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleNewRoute = ConsoleNewRouteImport.update({
  id: '/console/new',
  path: '/console/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleFunctionIdRoute = ConsoleFunctionIdRouteImport.update({
  id: '/console/$functionId',
  path: '/console/$functionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console/$functionId': typeof ConsoleFunctionIdRoute
  '/console/new': typeof ConsoleNewRoute
  '/console/': typeof ConsoleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console/$functionId': typeof ConsoleFunctionIdRoute
  '/console/new': typeof ConsoleNewRoute
  '/console': typeof ConsoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console/$functionId': typeof ConsoleFunctionIdRoute
  '/console/new': typeof ConsoleNewRoute
  '/console/': typeof ConsoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/console/$functionId'
    | '/console/new'
    | '/console/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/console/$functionId' | '/console/new' | '/console'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/console/$functionId'
    | '/console/new'
    | '/console/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConsoleFunctionIdRoute: typeof ConsoleFunctionIdRoute
  ConsoleNewRoute: typeof ConsoleNewRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/console'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/new': {
      id: '/console/new'
      path: '/console/new'
      fullPath: '/console/new'
      preLoaderRoute: typeof ConsoleNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/$functionId': {
      id: '/console/$functionId'
      path: '/console/$functionId'
      fullPath: '/console/$functionId'
      preLoaderRoute: typeof ConsoleFunctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConsoleFunctionIdRoute: ConsoleFunctionIdRoute,
  ConsoleNewRoute: ConsoleNewRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
